import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {after,test} from 'node:test';
import * as gate from '../swarm-gate.mjs';
const roots=[];after(()=>roots.forEach(r=>fs.rmSync(r,{recursive:true,force:true})));
const sha='a'.repeat(40),repairSha='b'.repeat(40);
function fixture(extra={}){
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'finish-line-'));roots.push(root);
  for(const d of ['registry','overlay','bin'])fs.mkdirSync(path.join(root,d));
  fs.writeFileSync(path.join(root,'bin/codex'),'#!/bin/sh\nexit 99\n',{mode:0o755});
  const identity={id:'codex-local',account:'fixture',environment:root.replace(/\\/g,'/').toLowerCase(),authenticated:true,source:'nonsecret fixture',at:new Date().toISOString()};
  fs.writeFileSync(path.join(root,'registry/swarm-current-identities.json'),JSON.stringify({identities:[identity]}));
  fs.writeFileSync(path.join(root,'registry/swarm-proven-routes.json'),JSON.stringify({routes:[{...identity,jobId:'q',model:'fixture',effort:'strong',access:'scratch',result:'passed',evidence:'q.log',returnRef:'q'}]}));
  fs.writeFileSync(path.join(root,'overlay/ROUTES.md'),`| Resource | Kind | CLI | Home | Dispatch | Model | Effort |\n|---|---|---|---|---|---|---|\n| codex-local | local | codex | ${root} | task | fixture | strong |\n`);
  const env={...process.env,BG_SWARM_DIR:path.join(root,'registry'),BGZFLOW_OVERLAY:path.join(root,'overlay'),CODEX_HOME:root,PATH:path.join(root,'bin')+path.delimiter+process.env.PATH};
  const config={resources:['codex-local'],limit:'Medium',wave0Sha:sha,releaseId:'release-1',pieces:{p:{owns:[]}},policy:{models:['fixture'],efforts:{default:['strong']}},...extra};
  gate.startSwarm(root,'s',config,env);
  const record=(type,value)=>gate.recordState(root,type,value,'s',{env});
  record('piece',{piece:'p',status:'deferred',reason:'No source worker needed for this gate fixture'});record('candidate',{sha});
  record('result',{stage:'suite',sha,status:'passed',exitCode:0,evidence:'suite.log'});record('result',{stage:'journey',sha,status:'passed',exitCode:0,evidence:'journey.log'});
  const rehearsal=(value={})=>record('rehearsal',{sha,goldenJourneys:'passed',rollbackProven:true,exitCode:0,evidence:'rehearsal.log',rollbackEvidence:'rollback.log',steps:['Open','Submit','Confirm'],...value});
  function dispatch(id,target='candidate'){
    const file=path.join(root,id+'.md');fs.writeFileSync(file,`SWARM: s\nPIECE: p\nKIND: check\nOWNS: []\nREAD_ONLY: true\nCHECK: review\nRELEASE_ID: release-1\nREVIEW_TARGET: ${target}\n\nRead bg-efficiency test-driven-development systematic-debugging verification-before-completion. Fast checks only. Proof handback.\n`);
    return gate.checkDispatch(root,{jobId:id,resource:'codex-local',cwd:root,command:`cx task --model fixture --effort strong --prompt-file "${file}"`},{reserve:true,env});
  }
  return {root,env,config,record,rehearsal,dispatch,state:()=>gate.status(root,'s',env),release:()=>gate.checkStage(root,'release',gate.status(root,'s',env).candidateSha,'s')};
}
test('FL1 release opens on exact passing rehearsal and rollback, without a ready verdict',()=>{const f=fixture();assert.equal(f.release().allowed,false);assert.equal(f.rehearsal().allowed,true);assert.equal(f.release().allowed,true);assert.equal(f.state().results.review,undefined);assert.equal(gate.checkStage(f.root,'release',repairSha,'s').allowed,false);});
for(const [label,value]of [['failed journeys',{goldenJourneys:'failed',exitCode:1}],['missing rollback',{rollbackProven:false}],['stale SHA',{sha:repairSha}]])test('FL2 release refuses '+label,()=>{const f=fixture();f.rehearsal(value);assert.equal(f.release().allowed,false);});
test('FL3 only one independent review dispatch is allowed per release ID, even in a new swarm',()=>{const f=fixture();f.rehearsal();assert.equal(f.dispatch('one').allowed,true);assert.equal(f.dispatch('two').rule,'review-limit');f.record('job',{id:'one',status:'completed',returnRef:sha,evidence:'review.log'});f.record('result',{stage:'review',sha,status:'passed',exitCode:0,evidence:'review.log'});assert.equal(gate.checkStage(f.root,'review',sha,'s').rule,'review-limit');f.record('finish',{});gate.startSwarm(f.root,'next',f.config,f.env);gate.recordState(f.root,'piece',{piece:'p',status:'deferred',reason:'fixture'},'next');gate.recordState(f.root,'candidate',{sha},'next');assert.equal(gate.checkStage(f.root,'review',sha,'next').rule,'review-limit');});
test('FL4 review of an explicit repair or a fix-wave candidate is refused',()=>{const f=fixture();f.rehearsal();assert.equal(f.dispatch('repair','repair').rule,'review-repair');f.record('candidate',{sha:repairSha,repair:true});assert.equal(gate.checkStage(f.root,'review',repairSha,'s').rule,'review-repair');});
for(const category of ['wrong-money','data-loss','security','privacy','missing-rollback','unapproved-stop-path'])test('FL5 reproduced '+category+' is a release blocker',()=>{const f=fixture();f.rehearsal();f.record('finding',{id:'F1',status:'open',category,reproduction:'Run the failing fixture; expected invariant is violated',detail:'Confirmed defect'});assert.equal(f.release().allowed,false);f.record('finding',{id:'F1',status:'closed',sha,evidence:'repair-rehearsal.log'});assert.equal(f.release().allowed,true);});
for(const category of ['design','performance','style','unknown'])test('FL6 reviewer '+category+' goes after-launch even when labelled blocking',()=>{const f=fixture();f.rehearsal();f.record('finding',{id:'F1',status:'open',category,blocking:true,reproduction:'Fixture reproduces the issue',detail:'Review finding'});assert.equal(f.release().allowed,true);assert.equal(f.state().findings.F1.disposition,'after-launch');});
test('FL7 an unreproduced critical claim is flagged to the lead, not a review blocker',()=>{const f=fixture();f.rehearsal();f.record('finding',{id:'F1',status:'open',category:'security',blocking:true,detail:'Unconfirmed claim'});assert.equal(f.release().allowed,true);assert.equal(f.state().findings.F1.blocking,false);});
test('FL8 repaired SHA is proved by a new rehearsal without another suite or review',()=>{const f=fixture();f.rehearsal();f.record('result',{stage:'review',sha,status:'passed',exitCode:0,evidence:'review.log',verdict:'changes-required'});f.record('candidate',{sha:repairSha,repair:true});assert.equal(f.release().allowed,false);assert.equal(f.rehearsal({sha:repairSha}).allowed,true);assert.equal(f.release().allowed,true);assert.equal(f.dispatch('again').rule,'review-repair');});
test('FL9 UI releases require the founder final phone or capable-device design check',()=>{const f=fixture({uiChanging:true,designOwner:'founder'});f.rehearsal();assert.equal(f.release().rule,'design-check');assert.throws(()=>f.record('design-check',{sha,status:'matched',authorisedBy:'reviewer',reason:'Looks fine',chatRef:'chat-1',device:'phone'}));f.record('design-check',{sha,status:'mismatch',authorisedBy:'founder',reason:'Does not match approved design',chatRef:'chat-2',device:'phone'});assert.equal(f.release().rule,'design-match');f.record('design-check',{sha,status:'matched',authorisedBy:'founder',reason:'Matches on capable device',chatRef:'chat-3',device:'capable-device'});assert.equal(f.release().allowed,true);f.record('candidate',{sha:repairSha,repair:true});f.rehearsal({sha:repairSha});assert.equal(f.release().rule,'design-check');});
test('FL10 non-UI releases never require a human design check',()=>{const f=fixture({uiChanging:false});f.rehearsal();assert.equal(f.release().allowed,true);});
test('FL11 failed or repeated review records cannot create an endless verdict loop',()=>{const f=fixture();f.rehearsal();assert.equal(f.record('result',{stage:'review',sha,status:'failed',exitCode:1,evidence:'review.log',verdict:'NO-GO'}).allowed,true);assert.equal(f.release().allowed,true);assert.equal(f.record('result',{stage:'review',sha,status:'passed',exitCode:0,evidence:'second.log'}).rule,'review-limit');});
test('FL12 an unapproved customer-facing stop path with its stopped journey blocks; the record shows it as a blocker',()=>{const f=fixture();f.rehearsal();f.record('finding',{id:'S1',status:'open',category:'unapproved-stop-path',reproduction:'Customer posts while a new review hold is on; the post stays queued and never publishes',detail:'New posting hold with no founder approval on the decisions page'});assert.equal(f.release().allowed,false);const s=f.state().findings.S1;assert.equal(s.blocking,true);assert.equal(s.disposition,'blocker');f.record('finding',{id:'S1',status:'closed',sha,evidence:'hold-removed-rehearsal.log'});assert.equal(f.release().allowed,true);});
test('FL13 an unapproved stop path claim without the stopped journey is flagged to the lead, not a blocker',()=>{const f=fixture();f.rehearsal();f.record('finding',{id:'S2',status:'open',category:'unapproved-stop-path',detail:'Possible new cap'});assert.equal(f.release().allowed,true);assert.equal(f.state().findings.S2.blocking,false);assert.ok((f.state().warnings||[]).some(w=>/S2 needs reproduction/.test(w.message)));});
