import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';import {after,test} from 'node:test';
import * as gate from '../swarm-gate.mjs';
const roots=[];after(()=>roots.forEach(r=>fs.rmSync(r,{recursive:true,force:true})));
const settings={light:{model:'fast',effort:'quick'},standard:{model:'strong',effort:'maximal'},'heavy-write':{model:'strong',effort:'maximal'},'heavy-read':{model:'strong',effort:'deep',readOnly:true,selfSplit:true}};
function f(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'gate-connected-'));roots.push(root);const git=(...a)=>{const r=spawnSync('git',a,{cwd:root,encoding:'utf8'});assert.equal(r.status,0,r.stderr);return r.stdout.trim();};git('init','-q');fs.writeFileSync(path.join(root,'a.mjs'),'export const a=1;\n');fs.writeFileSync(path.join(root,'a.test.mjs'),"import {test} from 'node:test';test('basic behaviour',()=>{});\n");git('add','.');git('-c','user.name=BGZFLOW','-c','user.email=bgzflow@users.noreply.github.com','commit','-qm','fixture');const sha=git('rev-parse','HEAD'),registry=path.join(root,'registry'),overlay=path.join(root,'overlay'),bin=path.join(root,'bin');for(const d of [registry,overlay,bin])fs.mkdirSync(d);fs.writeFileSync(path.join(bin,'codex'),'#!/bin/sh\nexit 99\n',{mode:0o755});fs.writeFileSync(path.join(overlay,'ROUTES.md'),'| Resource | Kind | CLI | Dispatch |\n|---|---|---|---|\n| codex-local | local | codex | supported task |\n');const scope=root.replace(/\\/g,'/').toLowerCase(),identity={id:'codex-local',account:'fixture',environment:scope,authenticated:true,source:'safe fixture',at:new Date().toISOString()};fs.writeFileSync(path.join(registry,'swarm-current-identities.json'),JSON.stringify({identities:[identity]}));fs.writeFileSync(path.join(registry,'swarm-proven-routes.json'),JSON.stringify({routes:Object.values(settings).map((s,i)=>({...identity,...s,observed:{model:s.model,effort:s.effort},jobId:'qualification-'+i,access:'scratch',returnRef:sha,evidence:'proof.json',result:'passed'}))}));const env={...process.env,BGZFLOW_PROJECT:root,BG_SWARM_DIR:registry,BGZFLOW_OVERLAY:overlay,CODEX_HOME:root,PATH:bin+path.delimiter+process.env.PATH};const config={resources:['codex-local'],limit:'Large',wave0Sha:sha,policy:{providers:{'codex-local':{family:'a',mapping:settings}},preference:['codex-local'],escalation:{enabled:true}},pieces:{p:{owns:['a.mjs','a.test.mjs'],goal:'Return a valid result'},alias:{owns:['b.mjs'],goal:'Return a valid result'}}};return {root,sha,env,config};}
function start(v){gate.startSwarm(v.root,'s',v.config,v.env);}
function dispatch(v,id,{piece='p',kind='build',model='strong',effort='maximal',readOnly=false,targetKind,body='',unsplit=false}={}){const brief=path.join(v.root,id+'.md');fs.writeFileSync(brief,`SWARM: s\nPIECE: ${piece}\nKIND: ${kind}\nOWNS: ${JSON.stringify(readOnly?[]:piece==='p'?['a.mjs','a.test.mjs']:['b.mjs'])}\n${readOnly?'READ_ONLY: true\n':''}${unsplit?'UNSPLIT: true\n':''}${targetKind?'TARGET_KIND: '+targetKind+'\n':''}\nRead bg-efficiency test-driven-development systematic-debugging verification-before-completion. Fast checks only. Proof handback with real output. Done when the valid-result test passes.\n${body}`);return gate.checkDispatch(v.root,{jobId:id,resource:'codex-local',command:`cx task --model ${model} --effort ${effort} --prompt-file "${brief}"`,cwd:v.root},{reserve:true,env:v.env});}
function fail(v,id,error='assertion logic failed'){gate.recordState(v.root,'job',{id,status:'failed',error,evidence:'failed.log'});}
function complete(v,id){gate.recordState(v.root,'job',{id,status:'completed',returnRef:v.sha,evidence:'worker.json'});}
function proof(v,id='job'){const env={...process.env};delete env.NODE_TEST_CONTEXT;const r=spawnSync(process.execPath,['--test','--test-reporter=tap','a.test.mjs'],{cwd:v.root,env,encoding:'utf8'});fs.writeFileSync(path.join(v.root,'fast.log'),r.stdout);const file=path.join(v.root,'handback.json');fs.writeFileSync(file,JSON.stringify({jobId:id,source:{baseSha:v.sha,sha:v.sha},checks:[{argv:['node','--test','a.test.mjs'],exitCode:r.status,stdoutFile:'fast.log',counts:{tests:1,pass:1,fail:0,skip:0}}]}));return file;}
test('I1 returned handback cannot enter integration without passing admission; failures return to the same job',()=>{const v=f();start(v);assert.equal(dispatch(v,'job').allowed,true);complete(v,'job');const r=gate.recordState(v.root,'piece',{piece:'p',status:'returned',returnRef:v.sha,evidence:'claim only',jobId:'job'});assert.equal(r.allowed,false);assert.equal(r.rule,'admission');assert.match(r.next,/job/);assert.equal(gate.status(v.root,undefined,v.env).failures['p:build'].count,1);assert.equal(gate.status(v.root,undefined,v.env).pieces.p.status,'pending');});
test('I2 passing evidence is admitted and repeated pickup is idempotent',()=>{const v=f();start(v);dispatch(v,'job');complete(v,'job');const value={piece:'p',status:'returned',returnRef:v.sha,evidence:'handback.json',handbackFile:proof(v),jobId:'job'};assert.equal(gate.recordState(v.root,'piece',value).allowed,true);assert.equal(gate.recordState(v.root,'piece',value).allowed,true);assert.equal(gate.status(v.root,undefined,v.env).pieces.p.admission.counts.tests,1);});
test('I3 renamed identical work inherits failed-twice restriction without a Jev call',()=>{const v=f();start(v);dispatch(v,'a');fail(v,'a');dispatch(v,'b');fail(v,'b');const r=dispatch(v,'alias-job',{piece:'alias'});assert.equal(r.allowed,false);assert.equal(r.rule,'diagnose');});
test('I4 simultaneous same goal on disjoint files blocks duplicate work',()=>{const v=f();start(v);dispatch(v,'a');assert.equal(dispatch(v,'duplicate',{piece:'alias'}).rule,'duplicate');});
test('L1 two logic failures require the heavy-read diagnosis and forbid a lower setting',()=>{const v=f();start(v);dispatch(v,'a');fail(v,'a');dispatch(v,'b');fail(v,'b');const low=dispatch(v,'d',{kind:'diagnose',targetKind:'build',readOnly:true,unsplit:true});assert.equal(low.allowed,false);assert.match(low.correctedCommand,/deep/);assert.equal(dispatch(v,'d2',{kind:'diagnose',targetKind:'build',readOnly:true,unsplit:true,effort:'deep'}).allowed,true);});
for(const [error,cause,rule]of [['missing dependency executable','environment','environment'],['authentication failed login required','environment','environment'],['flaky test timing infrastructure','flaky','flaky'],['unclear acceptance contract','spec','spec'],['assertion wrong result','logic','diagnose']])test(`L2 failure class routes correctly: ${cause} / ${error}`,()=>{const v=f();start(v);dispatch(v,'a');fail(v,'a',error);dispatch(v,'b');fail(v,'b',error);assert.equal(dispatch(v,'third').rule,rule);});
test('L3 post-root-cause retry uses heavy-write, needs the note and fails to the human once',()=>{const v=f();start(v);dispatch(v,'a');fail(v,'a');dispatch(v,'b');fail(v,'b');dispatch(v,'d',{kind:'diagnose',targetKind:'build',readOnly:true,unsplit:true,effort:'deep'});complete(v,'d');const note='Cause\nWrong branch in validation.\nEvidence\nThe invalid-input check fails.';gate.recordState(v.root,'root-cause',{piece:'p',kind:'build',note});assert.equal(dispatch(v,'retry').rule,'root-cause');assert.equal(dispatch(v,'retry2',{body:note}).allowed,true);fail(v,'retry2');assert.equal(dispatch(v,'last',{body:note}).rule,'human-failure');assert.equal(gate.status(v.root,undefined,v.env).escalated.jobs,2);});
test('L4 strongest read-only setting refuses all write kinds',()=>{const v=f();start(v);assert.equal(dispatch(v,'write',{effort:'deep'}).allowed,false);});
test('L5 recurring blocking finding after two fix waves enters the same failure ladder',()=>{const v=f();start(v);gate.recordState(v.root,'fix-wave',{});gate.recordState(v.root,'finding',{id:'wrong',piece:'p',status:'open',category:'wrong-money',reproduction:'Fixture charges the wrong amount',blocking:true,detail:'wrong result'});gate.recordState(v.root,'fix-wave',{});gate.recordState(v.root,'finding',{id:'wrong',piece:'p',status:'open',category:'wrong-money',reproduction:'Fixture charges the wrong amount',blocking:true,detail:'wrong result'});assert.equal(dispatch(v,'fix',{kind:'fix'}).rule,'diagnose');});
test('L6 environment remediation has proof and resumes the normal tier',()=>{const v=f();start(v);dispatch(v,'a');fail(v,'a','missing dependency executable');dispatch(v,'b');fail(v,'b','missing dependency executable');gate.recordState(v.root,'remediation',{piece:'p',kind:'build',evidence:'dependency installed and command passed',reason:'Environment repaired'});assert.equal(dispatch(v,'retry').allowed,true);});
test('I5 Stop hook only blocks once, ordinary messages and outside swarms stay untouched',()=>{const v=f();start(v);v.config.policy.jev={enabled:false};const event={hook_event_name:'Stop',cwd:v.root,last_assistant_message:'Built the result. Checks passed.'};assert.deepEqual(gate.hook(event,v.env),{});assert.deepEqual(gate.hook({...event,last_assistant_message:'Can you accept the review?',stop_hook_active:true},v.env),{});});
function judging(v,probabilities){let calls=0;const runner=(cmd,args)=>{calls++;const request=JSON.parse(fs.readFileSync(args.at(-3),'utf8'));const answers=Object.fromEntries(Object.entries(request.questions).map(([id,q])=>[id,q.type==='choice'?{type:'choice',choice:'logic',confidence:.9}:{type:'noul',noul:probabilities[id]??(["done_when","planned_piece"].includes(id)?probabilities.brief:undefined)??1}]));fs.writeFileSync(args.at(-1),JSON.stringify({model:'fixture',answers,usage:{input_tokens:9,output_tokens:2}}));return {status:0};};return {runner,calls:()=>calls};}
function enable(v){v.config.policy.jev={enabled:true,command:['fixture-judge'],timeoutMs:1000};}
function semanticDispatch(v,id,runner,piece='p'){const file=path.join(v.root,id+'.md');fs.writeFileSync(file,`SWARM: s\nPIECE: ${piece}\nKIND: build\nOWNS: ${JSON.stringify(v.config.pieces[piece].owns)}\n\nRead bg-efficiency test-driven-development systematic-debugging verification-before-completion. Fast checks only. Proof handback. Done when valid input produces a result.\n`);return gate.checkDispatch(v.root,{jobId:id,judgeRunner:runner,command:`cx task --model strong --effort maximal --prompt-file "${file}"`,resource:'codex-local',cwd:v.root},{reserve:true,env:v.env});}
test('IS1 reworded retry is bound to the failed step by one judgment batch',()=>{const v=f();enable(v);v.config.pieces.alias.goal='Validate replies and return a result';start(v);dispatch(v,'a');fail(v,'a');dispatch(v,'b');fail(v,'b');const j=judging(v,{retry_0:.9,brief:1});assert.equal(semanticDispatch(v,'alias',j.runner,'alias').rule,'diagnose');assert.equal(j.calls(),1);});
test('IS2 semantic duplicate on disjoint owned files blocks dispatch',()=>{const v=f();enable(v);v.config.pieces.alias.goal='Validate replies and return a result';start(v);dispatch(v,'a');const j=judging(v,{duplicate_0:.9,brief:1});assert.equal(semanticDispatch(v,'dup',j.runner,'alias').rule,'duplicate');assert.equal(j.calls(),1);});
for(const [noul,blocked]of [[.1,true],[.5,false],[.9,false]])test(`IS3 brief quality judgment ${noul}`,()=>{const v=f();enable(v);start(v);const j=judging(v,{brief:noul});const result=semanticDispatch(v,'brief',j.runner);assert.equal(result.allowed,!blocked);if(blocked)assert.equal(result.rule,'brief-quality');else if(noul===.5)assert.ok(gate.status(v.root,undefined,v.env).warnings.length);});
for(const [noul,blocked]of [[.9,true],[.5,false],[.1,false]])test(`IS4 Stop judgment ${noul}`,()=>{const v=f();enable(v);start(v);const j=judging(v,{stop:noul}),event={hook_event_name:'Stop',cwd:v.root,last_assistant_message:'Can you accept the review?'};const result=gate.hook(event,v.env,{judgeRunner:j.runner});assert.equal(result.decision==='block',blocked);assert.equal(j.calls(),1);assert.deepEqual(gate.hook({...event,stop_hook_active:true},v.env,{judgeRunner:j.runner}),{});assert.equal(j.calls(),1);});
test('IS5 Stop pre-filter and inactive swarms do not call Jev',()=>{const v=f();enable(v);start(v);const j=judging(v,{stop:1});assert.deepEqual(gate.hook({hook_event_name:'Stop',cwd:v.root,last_assistant_message:'The code and checks are complete.'},v.env,{judgeRunner:j.runner}),{});assert.equal(j.calls(),0);});
function releaseReady(v){gate.recordState(v.root,'piece',{piece:'p',status:'returned',returnRef:v.sha,evidence:'handback.json',handbackFile:proof(v)},undefined,{judgeRunner:judging(v,{}).runner});gate.recordState(v.root,'piece',{piece:'alias',status:'deferred',reason:'Optional alternative omitted'});gate.recordState(v.root,'candidate',{sha:v.sha});for(const stage of ['suite','journey'])gate.recordState(v.root,'result',{stage,sha:v.sha,status:'passed',exitCode:0,evidence:stage+'.log',steps:stage==='journey'?['Open page','Send form']:[]});gate.recordState(v.root,'rehearsal',{sha:v.sha,goldenJourneys:'passed',rollbackProven:true,rollbackEvidence:'rollback.log',exitCode:0,evidence:'rehearsal.log',steps:['Open page','Send form']});}
for(const [noul,blocked]of [[.1,true],[.5,false],[.9,false]])test(`IS6 journey coverage is an extra release condition ${noul}`,()=>{const v=f();enable(v);v.config.acceptanceScript=['Open the page','Submit the form','Confirm success'];start(v);releaseReady(v);const j=judging(v,{journey:noul});const r=gate.checkStage(v.root,'release',v.sha,undefined,{judgeRunner:j.runner});assert.equal(r.allowed,!blocked);assert.equal(j.calls(),1);});
test('IS7 Jev never opens an unready release ledger',()=>{const v=f();enable(v);v.config.acceptanceScript=['Open'];start(v);const j=judging(v,{journey:1});assert.equal(gate.checkStage(v.root,'release',v.sha,undefined,{judgeRunner:j.runner}).allowed,false);assert.equal(j.calls(),0);});
test('IS8 disabled semantic enforcement points make no paid dispatch call',()=>{const v=f();enable(v);v.config.policy.jev.enforcement={brief:false,retries:false,duplicate:false,classification:false};start(v);const j=judging(v,{brief:0});assert.equal(semanticDispatch(v,'disabled',j.runner).allowed,true);assert.equal(j.calls(),0);});
test('IS9 a blocked journey keeps the status release gate closed until new journey evidence',()=>{const v=f();enable(v);v.config.acceptanceScript=['Open page','Send form','Confirm success'];start(v);releaseReady(v);gate.checkStage(v.root,'release',v.sha,undefined,{judgeRunner:judging(v,{journey:0}).runner});assert.equal(gate.status(v.root,'s',v.env).releaseOpen,false);gate.recordState(v.root,'result',{stage:'journey',sha:v.sha,status:'passed',exitCode:0,evidence:'new-journey.log',steps:v.config.acceptanceScript});gate.recordState(v.root,'rehearsal',{sha:v.sha,goldenJourneys:'passed',rollbackProven:true,rollbackEvidence:'rollback.log',exitCode:0,evidence:'new-rehearsal.log',steps:v.config.acceptanceScript});assert.equal(gate.status(v.root,'s',v.env).releaseOpen,true);});
test('L9 a provider quota failure holds that tiered route without counting a logic failure',()=>{const v=f();start(v);dispatch(v,'a');fail(v,'a','quota exhausted');const r=dispatch(v,'b');assert.equal(r.allowed,false);assert.equal(r.rule,'resource');assert.ok(!gate.status(v.root,'s',v.env).failures['p:build']);gate.recordState(v.root,'route',{resource:'codex-local',available:true,evidence:'quota reset status',reason:'Provider is available again'});assert.equal(dispatch(v,'c').allowed,true);});
test('L10 conflicting thinking controls cannot bypass a configured provider tier',()=>{const v=f();v.config.policy.providers['codex-local'].mapping=structuredClone(settings);v.config.policy.providers['codex-local'].mapping.standard.thinking=true;const full=path.join(v.root,'registry/swarm-proven-routes.json'),data=JSON.parse(fs.readFileSync(full));for(const p of data.routes)p.observed.thinking=true;fs.writeFileSync(full,JSON.stringify(data));start(v);const file=path.join(v.root,'thinking.md');fs.writeFileSync(file,'SWARM: s\nPIECE: p\nKIND: build\nOWNS: ["a.mjs"]\n\nRead bg-efficiency test-driven-development systematic-debugging verification-before-completion. Fast checks only. Proof handback.');for(const flags of ['--thinking --no-thinking','--thinking=false']){const r=gate.checkDispatch(v.root,{jobId:flags,resource:'codex-local',cwd:v.root,command:`cx task --model strong --effort maximal ${flags} --prompt-file "${file}"`},{env:v.env});assert.equal(r.allowed,false);assert.equal(r.rule,'policy');assert.ok(!r.correctedCommand.includes('--no-thinking'));assert.ok(r.correctedCommand.includes('--thinking'));}});
test('L11 environment/access failures refuse a heavy model diagnosis and require remediation',()=>{const v=f();start(v);dispatch(v,'a');fail(v,'a','missing credential');dispatch(v,'b');fail(v,'b','missing credential');const r=dispatch(v,'diag',{kind:'diagnose',effort:'deep',readOnly:true,unsplit:true,targetKind:'build'});assert.equal(r.allowed,false);assert.equal(r.rule,'environment');});
test('I6 two rejected handbacks cannot be bypassed by recording an undispatched third repair',()=>{const v=f();start(v);dispatch(v,'job');complete(v,'job');for(const i of [1,2]){const file=path.join(v.root,`bad-${i}.json`);fs.writeFileSync(file,JSON.stringify({attempt:i,checks:[]}));assert.equal(gate.recordState(v.root,'piece',{piece:'p',status:'returned',returnRef:v.sha,evidence:file,jobId:'job'}).allowed,false);}const r=gate.recordState(v.root,'piece',{piece:'p',status:'returned',returnRef:v.sha,evidence:proof(v),jobId:'job'});assert.equal(r.allowed,false);assert.equal(r.rule,'diagnose');assert.equal(gate.status(v.root,'s',v.env).failures['p:build'].count,2);});
test('IS10 a recorded human emergency override cannot be revoked by a Jev judgment',()=>{const v=f();enable(v);v.config.acceptanceScript=['Open','Send','Confirm'];start(v);releaseReady(v);gate.recordState(v.root,'override',{sha:v.sha,authorisedBy:'human',reason:'Emergency accepted in chat',chatRef:'turn-9'});const j=judging(v,{journey:0});assert.equal(gate.checkStage(v.root,'release',v.sha,'s',{judgeRunner:j.runner}).allowed,true);assert.equal(j.calls(),0);});
test('L12 escalation status retains provider-reported usage and cost without estimating or exposing values',()=>{const v=f();start(v);dispatch(v,'a');fail(v,'a');dispatch(v,'b');fail(v,'b');dispatch(v,'diag',{kind:'diagnose',readOnly:true,unsplit:true,targetKind:'build',effort:'deep'});gate.recordState(v.root,'job',{id:'diag',status:'completed',returnRef:v.sha,evidence:'diagnosis.log',usage:{input_tokens:41,output_tokens:9,cost_credits:0.012,currency:'credits',api_key:'private'}});const s=gate.status(v.root,'s',v.env);assert.equal(s.escalated.reportedUsage[0].usage.cost_credits,0.012);assert.equal(s.escalated.reportedUsage[0].usage.input_tokens,41);assert.ok(!JSON.stringify(s.escalated).includes('private'));});
test('L8 one proven different-family diagnosis can run alongside the primary read-only investigation',()=>{const v=f();v.config.policy.escalation.crossFamilyDiagnosis=true;v.config.resources.push('grok-local');v.config.policy.providers['grok-local']={family:'b',mapping:settings};fs.writeFileSync(path.join(v.root,'bin/grok'),'#!/bin/sh\nexit 99\n',{mode:0o755});fs.appendFileSync(path.join(v.root,'overlay/ROUTES.md'),'| grok-local | local | grok | supported task |\n');for(const file of ['swarm-current-identities.json','swarm-proven-routes.json']){const full=path.join(v.root,'registry',file),data=JSON.parse(fs.readFileSync(full,'utf8')),key=file.includes('identities')?'identities':'routes';data[key].push(...data[key].map(x=>({...x,id:'grok-local',account:'other'})));fs.writeFileSync(full,JSON.stringify(data));}start(v);dispatch(v,'a');fail(v,'a');dispatch(v,'b');fail(v,'b');assert.equal(dispatch(v,'primary',{kind:'diagnose',readOnly:true,unsplit:true,targetKind:'build',effort:'deep'}).allowed,true);const brief=path.join(v.root,'independent.md');fs.writeFileSync(brief,'SWARM: s\nPIECE: p\nKIND: diagnose\nOWNS: []\nREAD_ONLY: true\nUNSPLIT: true\nTARGET_KIND: build\nCROSS_FAMILY: true\n\nRead bg-efficiency test-driven-development systematic-debugging verification-before-completion. Fast checks only. Proof handback.\n');const input={jobId:'other-family',resource:'grok-local',cwd:v.root,command:`grok --model strong --reasoning-effort deep --permission-mode plan --prompt-file "${brief}"`};assert.equal(gate.checkDispatch(v.root,input,{reserve:true,env:v.env}).allowed,true);assert.equal(gate.checkDispatch(v.root,{...input,jobId:'second-other'},{reserve:true,env:v.env}).allowed,false);});
