import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {after,test} from 'node:test';
const api=await import('../judgment.mjs').catch(()=>({}));
const root=fs.mkdtempSync(path.join(os.tmpdir(),'gate-judgment-'));after(()=>fs.rmSync(root,{recursive:true,force:true}));
const config={enabled:true,command:['python','judge.py'],timeoutMs:1200};
const unsafeEmail=['person','example.invalid'].join('@'),unsafeHome=['C:','Us'+'ers','Private','work'].join('/');
const evidence={goal:'Return validation errors for invalid input',files:['answer.mjs','answer.test.mjs'],testNames:['invalid input returns an error'],diffSummary:'2 changed files; 12 added lines',fastOutput:'# tests 1\n# pass 1\n# fail 0\n# skipped 0\n'};
function batch(event,noul,{enabled=true,choice}={}) {
  assert.equal(typeof api.judgeEvent,'function');let calls=0,payload;
  const runner=(cmd,args,opts)=>{calls++;payload=JSON.parse(fs.readFileSync(args.at(-3),'utf8'));const answers=Object.fromEntries(Object.entries(payload.questions).map(([id,q])=>[id,q.type==='choice'?{type:'choice',choice:choice||'logic',confidence:0.95}:{type:'noul',noul}]));fs.writeFileSync(args.at(-1),JSON.stringify({model:'fixture-judgment',answers,usage:{input_tokens:17,output_tokens:3}}));return {status:0};};
  const r=api.judgeEvent(root,{...config,enabled},{event,eventId:event+'-'+noul,evidence,failed:[{step:'old:build',goal:'Return validation errors'}],running:[{id:'active-1',goal:'Return validation errors'}]}, {runner});return {r,calls,payload};
}
for(const event of ['retry','duplicate','brief','stop','journey','admission'])for(const [level,violation] of [['block',0.9],['warn',0.6],['pass',0.1]])test(`JV1 labelled ${event} violation ${level}`,()=>{const positive=['brief','journey','admission'].includes(event);const {r,calls}=batch(event,positive?1-violation:violation);assert.equal(calls,1);assert.equal(r.decision,level);assert.equal(r.usage.input_tokens,17);});
test('JV2 inclusive calibrated thresholds use 0.8 block, 0.4 warning',()=>{assert.equal(typeof api.violationDecision,'function');assert.equal(api.violationDecision(0.8),'block');assert.equal(api.violationDecision(0.4),'warn');assert.equal(api.violationDecision(0.399),'pass');});
test('JV3 dispatch batches retries, duplicates, quality and classification once',()=>{const {r,calls,payload}=batch('dispatch',0.1);assert.equal(calls,1);assert.ok(payload.questions.retry_0);assert.ok(payload.questions.duplicate_0);assert.ok(payload.questions.done_when);assert.ok(payload.questions.planned_piece);assert.ok(payload.questions.failure_class);assert.equal(r.failureClass,'logic');});
test('JV4 missing, error or timeout judgment falls back to code once with warning',()=>{assert.equal(typeof api.judgeEvent,'function');for(const result of [{status:1},{status:null,error:{code:'ETIMEDOUT'}}]){let calls=0;const r=api.judgeEvent(root,config,{event:'brief',eventId:'error-'+result.status,evidence},{runner:()=>{calls++;return result;}});assert.equal(r.decision,'pass');assert.ok(r.warning);assert.equal(calls,1);}const r=api.judgeEvent(root,{enabled:false},{event:'brief',evidence});assert.equal(r.called,false);});
test('JV5 sanitized evidence removes credentials, env values, private paths and customer records',()=>{assert.equal(typeof api.sanitizeEvidence,'function');const r=api.sanitizeEvidence({...evidence,goal:'Fix input; API_KEY=secret-value '+unsafeEmail+' '+unsafeHome,fastOutput:'customer: personal payload\nTOKEN=hidden\n# tests 1\n# pass 1',env:{SECRET:'hidden'},wholeFile:'hidden'});const text=JSON.stringify(r);for(const secret of ['secret-value',unsafeEmail,unsafeHome,'personal payload','hidden'])assert.ok(!text.includes(secret),secret);assert.ok(!('env'in r));});
test('JV6 stop filter avoids ordinary messages and stop_hook_active cannot loop',()=>{assert.equal(typeof api.stopPrefilter,'function');assert.equal(api.stopPrefilter('Built the validation path. Checks passed.',{}),false);assert.equal(api.stopPrefilter('Can you accept the review?',{}),true);assert.equal(api.stopPrefilter('Can you try this?',{stop_hook_active:true}),false);});
test('JV7 low-confidence failure classification goes to the lead',()=>{assert.equal(typeof api.judgmentResult,'function');const r=api.judgmentResult({answers:{failure_class:{type:'choice',choice:'spec',confidence:0.5}}},{failure_class:{type:'choice',criteria:{spec:'Unclear requirement'}}});assert.equal(r.failureClass,null);assert.ok(r.warning);});
test('JV8 repeated event evidence reuses one response and usage stays on that event',()=>{assert.equal(typeof api.judgeEvent,'function');let calls=0;const runner=(cmd,a)=>{calls++;fs.writeFileSync(a.at(-1),JSON.stringify({answers:{brief:{type:'noul',noul:1}},usage:{input_tokens:2,output_tokens:1}}));return {status:0};};const event={event:'brief',eventId:'stable-event',evidence};api.judgeEvent(root,config,event,{runner});api.judgeEvent(root,config,event,{runner});assert.equal(calls,1);});
test('JV10 one brief-quality batch distinguishes missing done-when checks from a planned-piece mismatch',()=>{const r=api.judgeEvent(root,config,{event:'dispatch',eventId:'missing-done-when',evidence},{runner:(cmd,args)=>{const q=JSON.parse(fs.readFileSync(args.at(-3),'utf8')).questions;assert.ok(q.done_when);assert.ok(q.planned_piece);fs.writeFileSync(args.at(-1),JSON.stringify({answers:{done_when:{type:'noul',noul:0},planned_piece:{type:'noul',noul:1}}}));return {status:0};}});assert.equal(r.decision,'block');assert.equal(r.matches.done_when.level,'block');assert.equal(r.matches.planned_piece.level,'pass');});


test('R5 bearer headers, API keys and standalone tokens never reach the judgment runner',()=>{
 const secrets=[['Bearer','FixtureAuth9Zx7Qw5Er3Ty1Ui'].join(''),['sk','-proj-','Ab9Cd8Ef7Gh6Ij5Kl4Mn3Op2Qr1St0'].join(''),['gh','p_','Ab9Cd8Ef7Gh6Ij5Kl4Mn3Op2Qr1St0'].join(''),'Zx9Qw8Er7Ty6Ui5Op4As3Df2Gh1Jk0Lm9Nb8Vc7',['eyJhbGciOi','JIUzI1NiJ9.','eyJzdWIiOiJmaXh0dXJlIn0.','bW9ja1NpZ25hdHVyZTkwMTI'].join('')];
 const leaked=`Authorization: Bearer ${secrets[0]}\nX-Api-Key: ${secrets[1]}\nstandalone ${secrets[2]} ${secrets[3]} ${secrets[4]}\n# tests 1\n# pass 1\n# fail 0\n# skipped 0`;
 let observed;
 const result=api.judgeEvent(root,config,{event:'admission',eventId:'R5-sanitized',evidence:{...evidence,fastOutput:leaked,files:[secrets[2]],testNames:[secrets[3]]},failed:[{step:'old',error:leaked}]},{runner:(cmd,args)=>{
  const raw=fs.readFileSync(args.at(-3),'utf8');observed=raw;for(const secret of secrets)assert.ok(!raw.includes(secret),'Synthetic credential escaped redaction');
  const q=JSON.parse(raw).questions;fs.writeFileSync(args.at(-1),JSON.stringify({answers:Object.fromEntries(Object.keys(q).map(id=>[id,{type:'noul',noul:1}]))}));return {status:0};
 }});
 for(const secret of secrets)assert.ok(!observed.includes(secret),'Synthetic credential reached runner');assert.equal(result.decision,'pass');assert.ok(observed.includes('# tests 1'));
});
